### ISSUE TITLE
Possible to join and then do a groupby?

### ISSUE THREAD

**Issue by tlnagy** [davidanthoff/Query.jl#104]
Say I have two dataframes that look like:

```julia
df1 = DataFrame(id=[1,2,3], rel_freq=[0.5, 1, 1.5], class=["a", "a", "c"])
df2 = DataFrame(id=[1,2,3,4], rel_freq=[0.75, 0.75, 1.75, 1], class=["a", "a", "c", "c"])
println(df1)
println(df2)

#output

3×3 DataFrames.DataFrame
│ Row │ id │ rel_freq │ class │
├─────┼────┼──────────┼───────┤
│ 1   │ 1  │ 0.5      │ "a"   │
│ 2   │ 2  │ 1.0      │ "a"   │
│ 3   │ 3  │ 1.5      │ "c"   │
4×3 DataFrames.DataFrame
│ Row │ id │ rel_freq │ class │
├─────┼────┼──────────┼───────┤
│ 1   │ 1  │ 0.75     │ "a"   │
│ 2   │ 2  │ 0.75     │ "a"   │
│ 3   │ 3  │ 1.75     │ "c"   │
│ 4   │ 4  │ 1.0      │ "c"   │
```

Is it possible to join them based on `id` and group by `class` and then compute the mean difference between the `rel_freq` columns in one query? 

Here's my attempt to do it in two queries:

```julia
x = @from i in df1 begin
    @join j in df2 on i.id equals j.id 
    @select {i.id, rel_freq1=i.rel_freq, rel_freq2=j.rel_freq, i.class}
    @collect DataFrame
end

y = @from i in x begin
    @group i by i.class into g
    @select {g.key, avg_freq=mean(g.rel_freq2-g.rel_freq1)}
    @collect DataFrame
end
```
I couldn't figure out what exactly what values `g` has so it's not complete. The desired dataframe is

```
2×2 DataFrames.DataFrame
│ Row │ class │ avg_freq_diff │
├─────┼───────┼───────────────┤
│ 1   │ "a"   │ 0.0           │
│ 2   │ "c"   │ 0.25          │
```

`a` = `((0.75-0.5)+(0.75-1))/2`
`c` = `(1.75-1.5)/1`

**Comment by davidanthoff** [comment]
Maybe like this:
````julia
x = @from i in df1 begin
    @join j in df2 on i.id equals j.id
    @select {i.id, rel_freq1=i.rel_freq, rel_freq2=j.rel_freq, i.class} into i
    @group i by i.class into g
    @select {class=g.key, avg_freq=mean(j->j.rel_freq2-j.rel_freq1, g)}
    @collect DataFrame
end
````
There are two differences to your code:
1. I use a ``@select ... into i`` clause. That is essentially like having two chained queries, i.e. after that statement only the ``i`` range variable is available and you can continue your query.
2. The way you compute the mean doesn't work. ``g`` is an array of named tuples (with the columns that you created in the first ``@select`` statement). ``g.fieldname`` is not valid julia code.

**Comment by tlnagy** [comment]
Awesome. Thanks for the feedback. So what I'm doing is slightly more complicated. I want to calculate pvalues using a Mann Whitney test between the diffs of the `rel_freqs` for all classes and compare them to class `c`. The following is my attempt to do this:

```julia
x = @from i in df1 begin
    @join j in df2 on i.id equals j.id
    @select {i.id, log2fc=log2(get(j.rel_freq)/get(i.rel_freq)), i.class} into k
    @let negcontrol = @from l in k begin # try to build a list of log2fc of the negative controls
        @where contains(l.class, "c")
        @select l.log2fc
        @collect
    end
    @group k by k.gene into g
    @let test = MannWhitneyUTest(map(j->get(j.log2fc), g), negcontrol) #compare this group versus neg controls
    @select {
        gene=g.key, 
        avg_freq=mean(j->j.log2fc, g),
        pval= -log10(pvalue(test)) # calculate p value for this group versus neg controls
    }
    @collect DataFrame
end
```

**Comment by davidanthoff** [comment]
@tlnagy Do you mind reposting this question over in https://discourse.julialang.org/, probably in the data domain? It probably makes more sense to have usage questions there, so that other users benefit from the as well, and use the issue tracker here purely for project management for the package.

I'll also add something along those lines to the README.

**Comment by tlnagy** [comment]
I had originally posted it here because I had thought it was a limitation of Query.jl, but it evolved into a question of usage so I think it's fair to move it. I posted my follow-up question here: https://discourse.julialang.org/t/accessing-full-dataframe-after-a-join-within-a-query-jl-query/3076

Thanks for the help!
