### ISSUE TITLE
InexactError() with @groupby when type of variable changes

### ISSUE THREAD

**Issue by asbisen** [davidanthoff/Query.jl#109]
First of all thanks for developing this excellent library. I noticed that there is potentially a bug that is encountered when the `@groupby` argument is used that changes the type (eg. Int64 to Float64)

Sample DataTable
```julia
dt = DataTable(year=[1991,1992,1991,1992], price=[122,31,23,44])
```

```julia
@from r in dt begin
    @group r.price by r.year into g
    @select {Year=g.key, MaxPrice=maximum(g)}
    @collect 
end
``` 
```
2-element Array{NamedTuples._NT_Year_MaxPrice{Nullable{Int64},Nullable{Int64}},1}:
 (Year = 1991, MaxPrice = 122)
 (Year = 1992, MaxPrice = 44) 
```
But if I use an aggregating function that changes the output from Int64 to Float64 I get InexactError()

```julia
@from r in dt begin
    @group r.price by r.year into g
    @select {Year=g.key, MeanPrice=mean(g)}
    @collect 
end
```
```
InexactError()

Stacktrace:
 [1] convert(::Type{Int64}, ::Float64) at ./float.jl:679
 [2] convert at /Users/abisen/.julia/v0.6/Query/src/operators.jl:21 [inlined]
 [3] Type at ./sysimg.jl:24 [inlined]
 [4] /(::Query.DataValue{Int64}, ::Int64) at /Users/abisen/.julia/v0.6/Query/src/operators.jl:158 ...
...
...
```

**Comment by davidanthoff** [comment]
Thanks. I just pushed an update to ``master`` that should fix this. If you can't use ``master`` right now (a bit tricky to setup, you need to clone ``IterableTables`` for it to work), you can also change the ``@group`` line to ``@group get(r.price) by r.year into g``.

Let me know if that works for you!

**Comment by asbisen** [comment]
Thanks the update did solve the issue.
