### ISSUE TITLE
What functions can @select handle?

### ISSUE THREAD

**Issue by tcovert** [davidanthoff/Query.jl#111]
I understand that Query provides nullable lifting of some unary and binary operators.  What is the best way to do lifting for functions that Query hasn't already provided a lifted method for?  For example, if I want to use julia's `replace` inside a query on a DataTable with NullableArray string columns, this code doesn't work:   
```
@from i in dt begin
       @where i.col1 == "Texas"
       @select {i.col2, col3 = replace(i.col3, "-", "")}
       @collect DataTable
end
```

however, if I manually extend `Base.replace()` in the standard way, it does.  Is this the way to go?

**Comment by davidanthoff** [comment]
You can use any arbitrary julia code within ``@select``. So if you extend ``Base.replace`` it would work, or you could write something like
````julia
@select {i.col2, col3= isnull(i.col3) ? Nullable{String}() : Nullable(replace(get(i.col3), "-", ""))}
````
as a one-off solution.

Things will change slightly with the next release of Query: First, I'm no longer using ``Nullable`` inside queries, instead missing values will be encoded as ``DataValue``. A ``DataValue`` is essentially the same thing as a ``Nullable``, only difference is that the type is under my control and I can add methods as I wish without type piracy.

I also hope to enable the dot lifting syntax from julia 0.6 for ``DataValue``. If I can pull that off, you will be able to just write:
````julia
@select {i.col2, col3 = replace.(i.col3, "-", "")}
````
to lift the call to ``replace``.

Oh, and please ask questions like this over at https://discourse.julialang.org/c/domain/data. That will a) preserve answers beyond me closing the issue and b) I'm trying to use the issue tracker as a todo list for this project.
