### ISSUE TITLE
Please add support for `missing` type -- instead of using `DataValue` and `isnull`. 

### ISSUE THREAD

**Issue by essenciary** [davidanthoff/Query.jl#168]
Per https://discourse.julialang.org/t/query-jl-with-filtering-by-missing-values-doesnt-seem-to-work/8507

**Comment by davidanthoff** [comment]
I'm going to close this for now. As I wrote over in the discourse thread, the way ``Missing`` works right now does not match with the requirements for a missing data story of Query.jl. Maybe someone will find a solution at some point, but right now I don't see a short or medium term path that would enable this.
