### ISSUE TITLE
Consider using {} syntax for NamedTuple construction

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/Query.jl#22]

**Comment by bramtayl** [comment]
Expressions like 

```julia
@select @NT( Name=>i.Name, Friendcount=>length(i.Friends))
```

seem redundant. Wouldn't

```julia
@select(Name, i.Name, Friendcount = length(i.Friends))
```

work just as well? Or am I missing something?

**Comment by davidanthoff** [comment]
The generic ``@select`` macro can return anything, from a NamedTuple (via the ``@NT``) macro to anything else. The whole ``@NT`` syntax actually has nothing to do with Query, it is the syntax from the NamedTuples package. Having said that, I am thinking about an easier way to select into NamedTuples, just haven't decided about a specific syntax yet.

**Comment by davidanthoff** [comment]
This is now implemented on master.
