### ISSUE TITLE
i short-hand

### ISSUE THREAD

**Issue by bramtayl** [davidanthoff/Query.jl#25]
Taking a page from DataFramesMeta.jl, I think a short-hand like

```julia
x = @with df begin
    @where :age>30. && :children > 2
    @select @NT(Name=>lowercase(:name))
    @collect DataFrame
end
```

might be nice as a shorthand for

```julia
x = @from i in df begin
    @where i.age>30. && i.children > 2
    @select @NT(Name=>lowercase(i.name))
    @collect DataFrame
end
```

**Comment by davidanthoff** [comment]
I actually think the scoping solution in LINQ is one of its main appeals. Not having to use some magical escape character to denote "I'm now referencing something in the dataframe scope" makes for a much cleaner design, imo. This gets especially clear once you look how this all interacts in ``@join`` and ``@let`` statements.
