### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by bramtayl** [davidanthoff/Query.jl#26]
I've taken a stab at working my way through query_translation.jl quite a few times and I've found it quite difficult to read. I was wondering if you think it might be useful to update the parser to parse PanQuery.QueryLanguage objects instead. I think this could have a few advantages:

It could greatly simplify the code (I think) by working recursively
It could hook the code into a preexisting query standard that others could make use of.

Of course, I could also update PanQuery to more closely conform with the standards established in Query.jl.

Anyway, let me know if you're interested and it's something I could take a stab at.

**Comment by davidanthoff** [comment]
query_translation.jl is a more or less direct implementation of section 7.16.2 in the C# spec. The numbered phases in the code correspond to the subsections in the spec, the "A", "B" etc. phases are custom phases that I added. If I understand the point of PanQuery, you wouldn't want to hook into Query in the query_translation process, instead it might be useful for transforming graphs of ``Queryable`` objects into e.g. SQL. The whole ``Queryable`` type hierarchy is incomplete at this point. Take a look at the ``collect`` function in the file source_sqlite.jl. It currently is a horrendous implementation, but the intention is to convert an object graph of Queryable instances into SQL...

Also, the whole design of Query is really well documented, if you just read anything about the design of LINQ ;) The Internals section in the documentation has links to some excellent resources. If you are interested in the design for translating ``Queryable`` object graphs into SQL, make sure to read the series on the Wayward blog that is linked there.

**Comment by bramtayl** [comment]
I've pushed some commits to PanQuery so now it includes a limited parser for Query.jl.

The parsing code is in src/query_conversions, and there is a short test in test/query_tests.jl. Note that, for the 6 macros I've implemented so far, PanQuery's parsing exactly matches Query.jl's.

**Comment by davidanthoff** [comment]
That looks pretty cool! What use case do you have in mind for this?

**Comment by bramtayl** [comment]
I was thinking of writing a similar parsers for both DataFramesMeta and jplyr. I'm hoping any forth-coming SQL translation packages will also take advantage of a PanQuery standard. That means users will only have to learn one query language to everything they could possibly want.

**Comment by davidanthoff** [comment]
Do make sure you understand the full LINQ spec... The queries in a ``@from`` clause might at first sight look like simple chained function calls, but there is actually a lot more going on. So make sure you understand for example how transparent identifiers are used etc.

My goal with Query.jl is certainly that its macro interface is the DSL that users will use. I'm all for more choice, so if you expose a different DSL that users can use, go for it! But I don't expect that I will replace the macro API in Query.jl with something like that.

I'll close this issue for now, given that there is nothing to be done on Query's side. Thanks for bringing this up, I'll make sure to watch the PanQuery repo to see how things progress there!
