### ISSUE TITLE
Syntax error in first example?

### ISSUE THREAD

**Issue by tcovert** [davidanthoff/Query.jl#53]
I get a curly brace syntax error on the very first example:

```
julia> using Query, DataFrames, NamedTuples

julia> df = DataFrame(name=["John", "Sally", "Kirk"], age=[23., 42., 59.], children=[3,5,2])
3×3 DataFrames.DataFrame
│ Row │ name    │ age  │ children │
├─────┼─────────┼──────┼──────────┤
│ 1   │ "John"  │ 23.0 │ 3        │
│ 2   │ "Sally" │ 42.0 │ 5        │
│ 3   │ "Kirk"  │ 59.0 │ 2        │

julia> x = @from i in df begin
           @where i.age>30. && i.children > 2
           @select {Name=lowercase(i.name)}
           @collect DataFrame
       end
ERROR: syntax: { } vector syntax is discontinued
```

I am running the current tagged version of DataFrames (0.8.3) and Query (0.0.3), on Julia 0.5.  Here is versioninfo():
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753* (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by davidanthoff** [comment]
That syntax only works on ``master``. I believe you copied the example from ``master``, not the tagged version, right?

**Comment by tcovert** [comment]
Good point, the examples for the tagged version use NamedTuple.  That said, the documentation link in the README for the tagged version takes me to this this particular example.

**Comment by davidanthoff** [comment]
Good point, I just pushed an update to the README so that it now points to the last tagged version of the documentation. I'll also try to tag a new version soonish that has the more convenient syntax you tried.
