### ISSUE TITLE
Nullable ^ op

### ISSUE THREAD

**Issue by lbollar** [davidanthoff/Query.jl#60]
I am trying to do the following.

```
df = DataFrame(x=rand(20), y=rand(20))

x = @from i in df begin
               @select {i.x ^ 2}
               @collect DataFrame
       end
```

With this example I get an error stating 

```
ERROR: MethodError: ^(::Nullable{Float64}, ::Int64) is ambiguous. Candidates:
  
^(x, p::Integer) at intfuncs.jl:144
  ^{T1<:Number,T2<:Number}(x::Nullable{T1}, y::T2) at /Users/lollar/.julia/v0.5/Query/src/operators.jl:70

```
If i change the 2 to a float as in 2. , it works just fine.

I am new and learning types in Julia, but it looks to me as if your ^ method in src/operators.jl has a method for numbers of two different types as long as they are subtypes of numbers.

Is this right or am I doing something wrong?

Love the work in this package.

**Comment by davidanthoff** [comment]
There is a really "greedy" definition for ``^`` in julia base ``^(x, p::Integer) = power_by_squaring(x,p)`` that is causing this problem. I wonder whether that should just be removed from base...

@nalimilan any opinion?

In general all the lifted nullable stuff will hopefully be moved out of Query soon and as a first step go into a NullableOps package, and then hopefully move to base.

**Comment by nalimilan** [comment]
There are no "greedy" method definitions in Julia: they are only fallbacks. If you define a more specific method it will win. In the present case, I think you just need to define `^(x::Nullable{Float64}, y::Number)`.

**Comment by lbollar** [comment]
So I can understand developing going forward, in this case why does 
`^{T1<:Number,T2<:Number}(x::Nullable{T1}, y::T2)`  
not get used? 

I would have thought this generic would have eliminated the need to write  
`^(x::Nullable{Float64}, y::Number)`

**Comment by nalimilan** [comment]
The problem is that `Integer` is more specific than `Number` for the second argument, so Julia doesn't know which definition is the most appropriate.

**Comment by davidanthoff** [comment]
This is solved by [this](https://github.com/davidanthoff/Query.jl/blob/master/src/operators.jl#L75) line on master. Unless you need this in a tagged version really urgently I would wait with tagging new versions until a few more features have accumulated.
