### ISSUE TITLE
Using Query with Dict / OrderedDict

### ISSUE THREAD

**Issue by femtotrader** [davidanthoff/Query.jl#78]
Hello,

I'd like to use query with a `Dict` (an `OrderedDict` in fact)

```julia
using DataStructures: OrderedDict
using Query

type User
    name
    age
end

d = OrderedDict(1=>User("Mike", 30), 2=>User("Paul",15))

q = @from user in d.vals begin
    @where user.age > 20
    @select user
    @collect
end

println(q)

1-element Array{User,1}:
 User("Mike",30)
```

but I'd like to keep results in an associative datastructure.

I tried

```julia
julia> q = @from (id, user) in d begin
           @where user.age > 20
           @select user
           @collect
       end
```

but it raises:

```
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]
 in select(::Query.EnumerableWhere{Pair{Int64,User},Query.EnumerableIterable{Pair{Int64,User},DataStructures.OrderedDict{Int64,User}},FunctionWrappers.FunctionWrapper{Bool,Tuple{Pair{Int64,User}}}}, ::Function, ::Expr) at /Users/scls/.julia/v0.5/Query/src/enumerable/enumerable_select.jl:7
```

Any idea?

Kind regards

Related issue: https://github.com/davidanthoff/Query.jl/issues/56

**Comment by davidanthoff** [comment]
The ``@from (id, user) in d begin`` syntax you use is not supported (although I really like it, might be worth adding it).

So you will have to start with ``@from i in d begin``. At that point ``i`` will contain ``Pair``s. If you want range variables ``id`` and ``user``, you could add some statements like ``@let user=i.first``.

If you want to eventually have the results as a ``Dict`` or ``OrderedDict``, you need to make sure that your ``@select`` statement produces ``Pair`` instances. So either you just say ``@select i`` (assuming that you had ``@select i from d``), or you could have something arbitrary like ``@select Pair(user.age, user)``.

Finally, I think ``@collect Dict`` should work, but ``@collect OrderedDict`` probably doesn't. But you can just leave the ``@collect`` statement out, i.e. end the query with a ``@select`` statement, and then pass the query into the ``OrderedDict`` constructor.

So here is how this might all look in the end:
````julia
q = @from i in d begin
    @let id=i.first
    @let user=i.second
    @where user.age > 20
    @select Pair(id,user)
end

new_d = OrderedDict(q)
````

println(q)

1-element Array{User,1}:
 User("Mike",30)

**Comment by femtotrader** [comment]
Thanks @davidanthoff for your very quick answer!
